title: Đèn Đỏ
description: Ghi chú của Đèn Đỏ

url: https://ghichu.ngaoduky.com
baseurl: ""
paginate_path: "page/:num"
permalink: /:title

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   youtube: ngaoduky
   instagram: ngaoduky
   twitter: ngaoduky
   facebook: ngaoduky.com
   email: ngaoduky.com@gmail.com

google_analytics: "UA-58263416-1"
fbappid: 249127368869539
